# Stage 1: Dependencies
FROM node:20-alpine AS deps
WORKDIR /app

# Copy package files from src directory
COPY src/package*.json ./

# Install dependencies
RUN npm ci

# Stage 2: Builder
FROM node:20-alpine AS builder
WORKDIR /app

# Accept build arguments for environment variables
ARG NEXT_PUBLIC_NODE_ENV
ARG NEXT_PUBLIC_API_BASE_URL
ARG NEXT_PUBLIC_APP_NAME
ARG NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
ARG NEXT_PUBLIC_AUTH_API_URL
ARG NEXT_PUBLIC_GATEWAY_API_URL
ARG NEXT_PUBLIC_GATEWAY_API_URL_PROD
ARG NEXT_PUBLIC_GATEWAY_API_URL_DEV
ARG NEXT_PUBLIC_WORKSPACE_URL
ARG NEXT_PUBLIC_NLP_SERVICE_URL
ARG NEXT_PUBLIC_NLP_GATEWAY_URL
ARG NEXT_PUBLIC_WS_GATEWAY_URL
ARG NEXT_PUBLIC_EMPLOYEE_API_URL

# Set environment variables from build args
ENV NEXT_PUBLIC_NODE_ENV=$NEXT_PUBLIC_NODE_ENV
ENV NEXT_PUBLIC_API_BASE_URL=$NEXT_PUBLIC_API_BASE_URL
ENV NEXT_PUBLIC_APP_NAME=$NEXT_PUBLIC_APP_NAME
ENV NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=$NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
ENV NEXT_PUBLIC_AUTH_API_URL=$NEXT_PUBLIC_AUTH_API_URL
ENV NEXT_PUBLIC_GATEWAY_API_URL=$NEXT_PUBLIC_GATEWAY_API_URL
ENV NEXT_PUBLIC_GATEWAY_API_URL_PROD=$NEXT_PUBLIC_GATEWAY_API_URL_PROD
ENV NEXT_PUBLIC_GATEWAY_API_URL_DEV=$NEXT_PUBLIC_GATEWAY_API_URL_DEV
ENV NEXT_PUBLIC_WORKSPACE_URL=$NEXT_PUBLIC_WORKSPACE_URL
ENV NEXT_PUBLIC_NLP_SERVICE_URL=$NEXT_PUBLIC_NLP_SERVICE_URL
ENV NEXT_PUBLIC_NLP_GATEWAY_URL=$NEXT_PUBLIC_NLP_GATEWAY_URL
ENV NEXT_PUBLIC_WS_GATEWAY_URL=$NEXT_PUBLIC_WS_GATEWAY_URL
ENV NEXT_PUBLIC_EMPLOYEE_API_URL=$NEXT_PUBLIC_EMPLOYEE_API_URL

# Copy dependencies from deps stage
COPY --from=deps /app/node_modules ./node_modules
COPY src/ .

# Set environment variable for production build
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

# Build the application
RUN npm run build

# Stage 3: Runner
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Create a non-root user
RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

# Copy necessary files from builder
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

# Set correct permissions
RUN chown -R nextjs:nodejs /app

USER nextjs

EXPOSE 8085

ENV PORT=8085
ENV HOSTNAME="0.0.0.0"

CMD ["node", "server.js"]
